### ISSUE TITLE
jar cannot run

### ISSUE THREAD

**Issue by yuqin11** [dengziming/janusgraph-util#6]
run command:
java -jar janusgraph-import-1.0-SNAPSHOT-executable.jar --into sstTable --janus-config-file janus.properties --skip-duplicate-nodes true --skip-bad-edges true --ignore-extra-columns true --ignore-empty-strings true --bulk-loading true --bad-tolerance 10000000 --processors 4 --id-type string --drop-keyspace-if-exists true --max-memory 4G  --nodes:person small/v_person.csv --nodes:person1 small/v_person1.csv --edges:friends small/e_friends.csv --edges:friends1 small/e_friends1.csv > log.log 2>&1 &

janus.properties:
gremlin.graph= org.janusgraph.core.JanusGraphFactory
storage.backend= cql
storage.cql.keyspace=graphtest
query.batch= true
query.force-index= true
storage.cql.compression= true
storage.cql.compression-block-size=4
storage.cql.read-consistency-level=ONE
storage.cql.write-consistency-level=ONE
storage.cql.local-core-connections-per-host=2
storage.cql.local-max-connections-per-host= 2
storage.cql.replication-factor=1
storage.hostname=9.109.52.166
ids.block-size= 10000000
schema.default=none
storage.batch-loading=true
storage.buffer-size=1024
index.ES.backend= elasticsearch
index.ES.hostname=9.109.52.166
index.ES.elasticsearch.client-only= true
index.ES.index-name= graphtest
index.ES.elasticsearch.create.ext.index.number_of_shards= 2
index.ES.elasticsearch.create.ext.index.number_of_replicas= 0
index.ES.elasticsearch.create.ext.index.refresh_interval= 600s
log.tx.key-consistent=true
cache.db-cache-size= 0.0
cache.db-cache-time= 0
graph.replace-instance-if-exists=true

Error
Caused by: InvalidRequestException(why:Can't find a column family janusgraph_ids in keyspace graphtest)
        at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14678)
        at org.apache.cassandra.thrift.Cassandra$multiget_slice_result$multiget_slice_resultStandardScheme.read(Cassandra.java:14633)
        at org.apache.cassandra.thrift.Cassandra$multiget_slice_result.read(Cassandra.java:14559)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
        at org.apache.cassandra.thrift.Cassandra$Client.recv_multiget_slice(Cassandra.java:741)
        at org.apache.cassandra.thrift.Cassandra$Client.multiget_slice(Cassandra.java:725)
        at org.janusgraph.diskstorage.cassandra.thrift.CassandraThriftKeyColumnValueStore.getNamesSlice(CassandraThriftKeyColumnValueStore.java:146)

**Comment by yuqin11** [comment]
would you please help me to use this package?
