### ISSUE TITLE
Input error: Could not find implementation class: org.janusgraph.diskstorage.lucene.LuceneIndex

### ISSUE THREAD

**Issue by ge200012** [dengziming/janusgraph-util#9]

**Comment by ge200012** [comment]
run 
java -jar janusgraph-import-1.0-SNAPSHOT-executable.jar \
--into /root/janusgraph-util-feature_cassandra3/databases/all2018701.db \
--janus-config-file /root/janusgraph-util-feature_cassandra3/janusgraph.properties \
--skip-duplicate-nodes true \
--skip-bad-relationships true \
--ignore-extra-columns true \
--ignore-empty-strings true \
--bad-tolerance 10000000 \
--processors 4 \
--id-type string \
--max-memory 4G \
--drop-keyspace-if-exists true \
--nodes:titan /root/janusgraph-util-feature_cassandra3/janusgraph-import/src/main/resources/v_titan.csv \
--nodes:location /root/janusgraph-util-feature_cassandra3/janusgraph-import/src/main/resources/v_location.csv \
--nodes:god /root/janusgraph-util-feature_cassandra3/janusgraph-import/src/main/resources/v_god.csv \
--nodes:demigod /root/janusgraph-util-feature_cassandra3/janusgraph-import/src/main/resources/v_demigod.csv \
--nodes:human /root/janusgraph-util-feature_cassandra3/janusgraph-import/src/main/resources/v_human.csv \
--nodes:monster /root/janusgraph-util-feature_cassandra3/janusgraph-import/src/main/resources/v_monster.csv \
--edges:father /root/janusgraph-util-feature_cassandra3/janusgraph-import/src/main/resources/e_god_titan_father.csv \
--edges:father /root/janusgraph-util-feature_cassandra3/janusgraph-import/src/main/resources/e_demigod_god_father.csv \
--edges:mother /root/janusgraph-util-feature_cassandra3/janusgraph-import/src/main/resources/e_demigod_human_mother.csv \
--edges:lives /root/janusgraph-util-feature_cassandra3/janusgraph-import/src/main/resources/e_god_location_lives.csv \
--edges:lives /root/janusgraph-util-feature_cassandra3/janusgraph-import/src/main/resources/e_monster_location_lives.csv \
--edges:brother /root/janusgraph-util-feature_cassandra3/janusgraph-import/src/main/resources/e_god_god_brother.csv \
--edges:battled /root/janusgraph-util-feature_cassandra3/janusgraph-import/src/main/resources/e_demigod_monster_battled.csv \
--edges:pet /root/janusgraph-util-feature_cassandra3/janusgraph-import/src/main/resources/e_god_monster_pet.csv 

Error:
14:09:26.524 [main] DEBUG o.a.c.c.PropertiesConfiguration - FileName set to janusgraph.properties
14:09:26.525 [main] DEBUG o.a.c.c.PropertiesConfiguration - Base path set to /root/janusgraph-util-feature_cassandra3
14:09:26.528 [main] DEBUG o.a.c.c.ConfigurationUtils - ConfigurationUtils.locate(): base is /root/janusgraph-util-feature_cassandra3, name is janusgraph.properties
14:09:26.528 [main] DEBUG o.a.c.c.DefaultFileSystem - Could not locate file janusgraph.properties at /root/janusgraph-util-feature_cassandra3: no protocol: /root/janusgraph-util-feature_cassandra3
14:09:26.528 [main] DEBUG o.a.c.c.ConfigurationUtils - Loading configuration from the path /root/janusgraph-util-feature_cassandra3/janusgraph.properties
14:09:26.632 [main] DEBUG o.j.d.c.t.t.CTConnectionFactory - Creating TSocket(127.0.0.1, 9160, null, null, 10000)
14:09:26.727 [main] DEBUG o.j.d.c.t.CassandraThriftStoreManager - Found existing keyspace janusgraph
14:09:26.738 [main] DEBUG o.j.d.c.t.t.CTConnectionFactory - Creating TSocket(127.0.0.1, 9160, null, null, 10000)
14:09:26.739 [main] DEBUG o.j.d.c.t.CassandraThriftStoreManager - Looking up metadata on keyspace janusgraph...
14:09:26.739 [main] DEBUG o.j.d.c.t.CassandraThriftStoreManager - Keyspace janusgraph and ColumnFamily system_properties were found.
14:09:26.754 [main] DEBUG o.j.d.cassandra.CassandraTransaction - Created CassandraTransaction@3c0be339[read=QUORUM,write=QUORUM]
14:09:26.776 [main] DEBUG o.j.d.cassandra.CassandraTransaction - Created CassandraTransaction@10959ece[read=QUORUM,write=QUORUM]
14:09:26.777 [main] DEBUG o.j.d.cassandra.CassandraTransaction - Created CassandraTransaction@3a6bb9bf[read=QUORUM,write=QUORUM]
14:09:26.779 [main] DEBUG o.j.d.cassandra.CassandraTransaction - Created CassandraTransaction@62230c58[read=QUORUM,write=QUORUM]
14:09:26.780 [main] DEBUG o.j.d.cassandra.CassandraTransaction - Created CassandraTransaction@2cd2a21f[read=QUORUM,write=QUORUM]
14:09:26.782 [main] DEBUG o.j.d.cassandra.CassandraTransaction - Created CassandraTransaction@2e55dd0c[read=QUORUM,write=QUORUM]
14:09:26.783 [main] DEBUG o.j.d.cassandra.CassandraTransaction - Created CassandraTransaction@1eb5174b[read=QUORUM,write=QUORUM]
14:09:26.785 [main] WARN  o.j.g.c.GraphDatabaseConfiguration - Local setting ids.block-size=10000000 (Type: GLOBAL_OFFLINE) is overridden by globally managed value (10000).  Use the ManagementSystem interface instead of the local configuration to control this setting.
14:09:26.785 [main] DEBUG o.j.d.cassandra.CassandraTransaction - Created CassandraTransaction@4e7912d8[read=QUORUM,write=QUORUM]
14:09:26.786 [main] WARN  o.j.g.c.GraphDatabaseConfiguration - Local setting index.search.backend=elasticsearch (Type: GLOBAL_OFFLINE) is overridden by globally managed value (lucene).  Use the ManagementSystem interface instead of the local configuration to control this setting.
14:09:26.787 [main] DEBUG o.j.d.cassandra.CassandraTransaction - Created CassandraTransaction@2f8dad04[read=QUORUM,write=QUORUM]
14:09:26.790 [main] INFO  o.j.d.c.t.CassandraThriftStoreManager - Closed Thrift connection pooler.
14:09:26.792 [main] INFO  o.j.g.c.GraphDatabaseConfiguration - Generated unique-instance-id=ac1669e4171137-node01
14:09:26.798 [main] DEBUG o.j.d.c.t.t.CTConnectionFactory - Creating TSocket(127.0.0.1, 9160, null, null, 10000)
14:09:26.806 [main] INFO  org.janusgraph.diskstorage.Backend - Configuring index [search]
Input error: Could not find implementation class: org.janusgraph.diskstorage.lucene.LuceneIndex
Caused by:Could not find implementation class: org.janusgraph.diskstorage.lucene.LuceneIndex
java.lang.IllegalArgumentException: Could not find implementation class: org.janusgraph.diskstorage.lucene.LuceneIndex
        at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:60)
        at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:476)
        at org.janusgraph.diskstorage.Backend.getIndexes(Backend.java:463)
        at org.janusgraph.diskstorage.Backend.<init>(Backend.java:148)
        at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1840)
        at org.janusgraph.graphdb.database.StandardJanusGraph.<init>(StandardJanusGraph.java:138)
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:160)
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:131)
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:78)
        at janusgraph.util.batchimport.unsafe.graph.GraphUtil.getGraph(GraphUtil.java:41)
        at janusgraph.util.batchimport.unsafe.BulkLoad.getGraph(BulkLoad.java:417)
        at janusgraph.util.batchimport.unsafe.BulkLoad.main(BulkLoad.java:284)
Caused by: java.lang.ClassNotFoundException: org.janusgraph.diskstorage.lucene.LuceneIndex
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:56)
        ... 11 more

How can I solve it?
